//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPSYNC {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.0.27;Database=TW01;User Id=attendence;\r\nPassword=89947155;")]
        public string DSCTPEConnection {
            get {
                return ((string)(this["DSCTPEConnection"]));
            }
            set {
                this["DSCTPEConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11;Initial Catalog=Attendance;User Id=regalsa ;Password=sA8" +
            "9947155;")]
        public string RegalConnection {
            get {
                return ((string)(this["RegalConnection"]));
            }
            set {
                this["RegalConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.0.27;Database=TW04;User Id=attendence;\r\nPassword=89947155;")]
        public string DSCTXGConnection {
            get {
                return ((string)(this["DSCTXGConnection"]));
            }
            set {
                this["DSCTXGConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.0.27;Database=TW06;User Id=attendence;\r\nPassword=89947155;")]
        public string DSCTNNConnection {
            get {
                return ((string)(this["DSCTNNConnection"]));
            }
            set {
                this["DSCTNNConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=192.168.0.27;Database=Regal_SU;User Id=attendence;\r\nPassword=89947155;")]
        public string DSCSUConnection {
            get {
                return ((string)(this["DSCSUConnection"]));
            }
            set {
                this["DSCSUConnection"] = value;
            }
        }
    }
}
